### PR TITLE
Align repo with changes to aks-module-network, fix logic in non-prod vnet peerings for AAT

### PR DESCRIPTION
**Pull request by danielwilsonkainos**
### Change description ###

* Fix logic for aat in non-prod vnet peerings for aat

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by timja — COMMENTED** [review]
Do the peerings for AAT change need any moved blocks?

**Comment by danielwilsonkainos** [comment]
> Do the peerings for AAT change need any moved blocks?

The moved blocks are in place but the generation of the name param was missing logic clause for AAT so resource was being force replaced. Can see the [TF Plan here](https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=391835&view=logs&j=3d4d5f0d-151b-5e82-4cb8-faa16997da6e&t=e317ea8e-0642-59a1-a5b9-c321e6978d6a) to see what i mean

**Comment by timja** [comment]
Is that an old plan? as it's replacing it without nonprod on the end

**Comment by danielwilsonkainos** [comment]
> Is that an old plan? as it's replacing it without nonprod on the end

yes, this is the error which has been fixed. You can see in there though that the moved blocks still do there thing. [This is the latest TF plan for AAT](https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=391868&view=logs&j=3d4d5f0d-151b-5e82-4cb8-faa16997da6e&t=e317ea8e-0642-59a1-a5b9-c321e6978d6a)

**Review by timja — APPROVED** [review]

**Pull request merged**
